import { EProductCategory, EProductSize, EProductTone, IProduct } from "@/interfaces";

export const PRODUCTS: IProduct[] = [
  {
    sku: "SKU1",
    name: "Cool Head",
    imageSrc: "https://img.freepik.com/free-photo/great-blue-hat_1203-1941.jpg?ga=GA1.1.844083129.1727363790&semt=ais_hybrid",
    category: EProductCategory.HAT,
    price: 38.41,
    sizes: [EProductSize.M, EProductSize.L],
    tones: [EProductTone.COOL],
  },
  {
    sku: "SKU2",
    name: "Straw Hat",
    imageSrc: "https://media.istockphoto.com/id/184397074/photo/straw-hat.jpg?b=1&s=612x612&w=0&k=20&c=PSYwaf1ObvRJiteRLEsJByXsa3EaF_4z4ng-HUNUXnY=",
    category: EProductCategory.HAT,
    price: 28.25,
    sizes: [EProductSize.S, EProductSize.M],
    tones: [EProductTone.COOL, EProductTone.WHITE],
  },
  {
    sku: "SKU3",
    name: "Slim Fit Jeans",
    imageSrc: "https://example.com/images/SKU3.jpg",
    category: EProductCategory.JEANS,
    price: 72.0,
    sizes: [EProductSize.M, EProductSize.L],
    tones: [EProductTone.BLACK, EProductTone.GRAY],
  },
  {
    sku: "SKU4",
    name: "Round Sunglasses",
    imageSrc: "https://example.com/images/SKU4.jpg",
    category: EProductCategory.GLASSES,
    price: 34.99,
    sizes: [EProductSize.S],
    tones: [EProductTone.COOL, EProductTone.BLACK],
  },
  {
    sku: "SKU5",
    name: "Running Shoes",
    imageSrc: "https://example.com/images/SKU5.jpg",
    category: EProductCategory.SHOES,
    price: 90.5,
    sizes: [EProductSize.M, EProductSize.L],
    tones: [EProductTone.GRAY, EProductTone.COOL],
  },
  {
    sku: "SKU6",
    name: "Leather Hat",
    imageSrc: "https://example.com/images/SKU6.jpg",
    category: EProductCategory.HAT,
    price: 55.72,
    sizes: [EProductSize.M, EProductSize.L],
    tones: [EProductTone.BLACK, EProductTone.GRAY],
  },
  {
    sku: "SKU7",
    name: "Plain T-Shirt",
    imageSrc: "https://example.com/images/SKU7.jpg",
    category: EProductCategory["T-SHIRT"],
    price: 18.95,
    sizes: [EProductSize.S, EProductSize.M],
    tones: [EProductTone.BLACK, EProductTone.WHITE],
  },
  {
    sku: "SKU8",
    name: "Bootcut Jeans",
    imageSrc: "https://example.com/images/SKU8.jpg",
    category: EProductCategory.JEANS,
    price: 65.4,
    sizes: [EProductSize.L, EProductSize.XL],
    tones: [EProductTone.GRAY, EProductTone.WARM],
  },
  {
    sku: "SKU9",
    name: "Aviator Sunglasses",
    imageSrc: "https://example.com/images/SKU9.jpg",
    category: EProductCategory.GLASSES,
    price: 49.99,
    sizes: [EProductSize.M],
    tones: [EProductTone.COOL, EProductTone.BLACK],
  },
  {
    sku: "SKU10",
    name: "Running Sneakers",
    imageSrc: "https://example.com/images/SKU10.jpg",
    category: EProductCategory.SHOES,
    price: 120.99,
    sizes: [EProductSize.M, EProductSize.L],
    tones: [EProductTone.COOL, EProductTone.BLACK],
  },
  {
    sku: "SKU11",
    name: "Straw Hat",
    imageSrc: "https://example.com/images/SKU11.jpg",
    category: EProductCategory.HAT,
    price: 45.0,
    sizes: [EProductSize.L],
    tones: [EProductTone.WHITE, EProductTone.COOL],
  },
  {
    sku: "SKU12",
    name: "V-Neck T-Shirt",
    imageSrc: "https://example.com/images/SKU12.jpg",
    category: EProductCategory["T-SHIRT"],
    price: 21.3,
    sizes: [EProductSize.S, EProductSize.M],
    tones: [EProductTone.GRAY, EProductTone.COOL],
  },
  {
    sku: "SKU13",
    name: "Distressed Jeans",
    imageSrc: "https://example.com/images/SKU13.jpg",
    category: EProductCategory.JEANS,
    price: 78.12,
    sizes: [EProductSize.M, EProductSize.L],
    tones: [EProductTone.BLACK, EProductTone.COOL],
  },
  {
    sku: "SKU14",
    name: "Sunglasses with Case",
    imageSrc: "https://example.com/images/SKU14.jpg",
    category: EProductCategory.GLASSES,
    price: 68.0,
    sizes: [EProductSize.M],
    tones: [EProductTone.BLACK, EProductTone.COOL],
  },
  {
    sku: "SKU15",
    name: "Sports Shoes",
    imageSrc: "https://example.com/images/SKU15.jpg",
    category: EProductCategory.SHOES,
    price: 110.0,
    sizes: [EProductSize.M, EProductSize.L],
    tones: [EProductTone.COOL, EProductTone.WHITE],
  },
  {
    sku: "SKU16",
    name: "Fedora Hat",
    imageSrc: "https://example.com/images/SKU16.jpg",
    category: EProductCategory.HAT,
    price: 60.99,
    sizes: [EProductSize.M, EProductSize.L],
    tones: [EProductTone.GRAY, EProductTone.BLACK],
  },
  {
    sku: "SKU17",
    name: "Printed T-Shirt",
    imageSrc: "https://example.com/images/SKU17.jpg",
    category: EProductCategory["T-SHIRT"],
    price: 24.75,
    sizes: [EProductSize.S, EProductSize.M],
    tones: [EProductTone.COOL, EProductTone.WHITE],
  },
  {
    sku: "SKU18",
    name: "Straight Jeans",
    imageSrc: "https://example.com/images/SKU18.jpg",
    category: EProductCategory.JEANS,
    price: 82.99,
    sizes: [EProductSize.M, EProductSize.L],
    tones: [EProductTone.GRAY, EProductTone.COOL],
  },
  {
    sku: "SKU19",
    name: "Retro Sunglasses",
    imageSrc: "https://example.com/images/SKU19.jpg",
    category: EProductCategory.GLASSES,
    price: 38.6,
    sizes: [EProductSize.M],
    tones: [EProductTone.COOL, EProductTone.BLACK],
  },
  {
    sku: "SKU20",
    name: "Casual Sneakers",
    imageSrc: "https://example.com/images/SKU20.jpg",
    category: EProductCategory.SHOES,
    price: 76.75,
    sizes: [EProductSize.M, EProductSize.L],
    tones: [EProductTone.BLACK, EProductTone.COOL],
  },
  {
    sku: "SKU21",
    name: "Bucket Hat",
    imageSrc: "https://example.com/images/SKU21.jpg",
    category: EProductCategory.HAT,
    price: 29.99,
    sizes: [EProductSize.M, EProductSize.L],
    tones: [EProductTone.BLACK, EProductTone.COOL],
  },
  {
    sku: "SKU22",
    name: "Cotton T-Shirt",
    imageSrc: "https://example.com/images/SKU22.jpg",
    category: EProductCategory["T-SHIRT"],
    price: 22.5,
    sizes: [EProductSize.S, EProductSize.M],
    tones: [EProductTone.WHITE, EProductTone.BLACK],
  },
  {
    sku: "SKU23",
    name: "Ripped Jeans",
    imageSrc: "https://example.com/images/SKU23.jpg",
    category: EProductCategory.JEANS,
    price: 79.99,
    sizes: [EProductSize.M, EProductSize.L],
    tones: [EProductTone.COOL, EProductTone.GRAY],
  },
  {
    sku: "SKU24",
    name: "Sunglasses for Men",
    imageSrc: "https://example.com/images/SKU24.jpg",
    category: EProductCategory.GLASSES,
    price: 44.25,
    sizes: [EProductSize.M],
    tones: [EProductTone.COOL, EProductTone.BLACK],
  },
  {
    sku: "SKU25",
    name: "Comfort Shoes",
    imageSrc: "https://example.com/images/SKU25.jpg",
    category: EProductCategory.SHOES,
    price: 98.55,
    sizes: [EProductSize.M, EProductSize.L],
    tones: [EProductTone.BLACK, EProductTone.GRAY],
  },
  {
    sku: "SKU26",
    name: "Straw Fedora",
    imageSrc: "https://example.com/images/SKU26.jpg",
    category: EProductCategory.HAT,
    price: 37.99,
    sizes: [EProductSize.L],
    tones: [EProductTone.WHITE, EProductTone.GRAY],
  },
  {
    sku: "SKU27",
    name: "Vintage T-Shirt",
    imageSrc: "https://example.com/images/SKU27.jpg",
    category: EProductCategory["T-SHIRT"],
    price: 31.5,
    sizes: [EProductSize.M, EProductSize.L],
    tones: [EProductTone.COOL, EProductTone.BLACK],
  },
  {
    sku: "SKU28",
    name: "Bootcut Jeans",
    imageSrc: "https://example.com/images/SKU28.jpg",
    category: EProductCategory.JEANS,
    price: 80.99,
    sizes: [EProductSize.L, EProductSize.M],
    tones: [EProductTone.GRAY, EProductTone.COOL],
  },
  {
    sku: "SKU29",
    name: "Oval Sunglasses",
    imageSrc: "https://example.com/images/SKU29.jpg",
    category: EProductCategory.GLASSES,
    price: 38.89,
    sizes: [EProductSize.M],
    tones: [EProductTone.BLACK, EProductTone.COOL],
  },
  {
    sku: "SKU30",
    name: "Casual Sneakers",
    imageSrc: "https://example.com/images/SKU30.jpg",
    category: EProductCategory.SHOES,
    price: 66.22,
    sizes: [EProductSize.M, EProductSize.L],
    tones: [EProductTone.GRAY, EProductTone.COOL],
  },
  {
    sku: "SKU31",
    name: "Wide-Brimmed Hat",
    imageSrc: "https://example.com/images/SKU31.jpg",
    category: EProductCategory.HAT,
    price: 43.75,
    sizes: [EProductSize.M],
    tones: [EProductTone.WHITE, EProductTone.COOL],
  },
  {
    sku: "SKU32",
    name: "Striped T-Shirt",
    imageSrc: "https://example.com/images/SKU32.jpg",
    category: EProductCategory["T-SHIRT"],
    price: 29.5,
    sizes: [EProductSize.M, EProductSize.L],
    tones: [EProductTone.GRAY, EProductTone.COOL],
  },
  {
    sku: "SKU33",
    name: "Plaid Jeans",
    imageSrc: "https://example.com/images/SKU33.jpg",
    category: EProductCategory.JEANS,
    price: 73.0,
    sizes: [EProductSize.M, EProductSize.L],
    tones: [EProductTone.BLACK, EProductTone.COOL],
  },
  {
    sku: "SKU34",
    name: "Oversized Sunglasses",
    imageSrc: "https://example.com/images/SKU34.jpg",
    category: EProductCategory.GLASSES,
    price: 51.22,
    sizes: [EProductSize.M],
    tones: [EProductTone.BLACK, EProductTone.COOL],
  },
  {
    sku: "SKU35",
    name: "Leather Sneakers",
    imageSrc: "https://example.com/images/SKU35.jpg",
    category: EProductCategory.SHOES,
    price: 130.99,
    sizes: [EProductSize.M, EProductSize.L],
    tones: [EProductTone.BLACK, EProductTone.GRAY],
  },
  {
    sku: "SKU36",
    name: "Stylish Fedora",
    imageSrc: "https://example.com/images/SKU36.jpg",
    category: EProductCategory.HAT,
    price: 49.99,
    sizes: [EProductSize.M],
    tones: [EProductTone.BLACK, EProductTone.GRAY],
  },
  {
    sku: "SKU37",
    name: "Classic T-Shirt",
    imageSrc: "https://example.com/images/SKU37.jpg",
    category: EProductCategory["T-SHIRT"],
    price: 23.99,
    sizes: [EProductSize.M, EProductSize.L],
    tones: [EProductTone.BLACK, EProductTone.WHITE],
  },
  {
    sku: "SKU38",
    name: "Leather Jeans",
    imageSrc: "https://example.com/images/SKU38.jpg",
    category: EProductCategory.JEANS,
    price: 98.65,
    sizes: [EProductSize.L, EProductSize.XL],
    tones: [EProductTone.GRAY, EProductTone.COOL],
  },
  {
    sku: "SKU39",
    name: "Sunglasses with Polarized Lenses",
    imageSrc: "https://example.com/images/SKU39.jpg",
    category: EProductCategory.GLASSES,
    price: 68.75,
    sizes: [EProductSize.M],
    tones: [EProductTone.COOL, EProductTone.BLACK],
  },
  {
    sku: "SKU40",
    name: "Tennis Shoes",
    imageSrc: "https://example.com/images/SKU40.jpg",
    category: EProductCategory.SHOES,
    price: 90.0,
    sizes: [EProductSize.M, EProductSize.L],
    tones: [EProductTone.GRAY, EProductTone.COOL],
  },
  {
    sku: "SKU41",
    name: "Summer Fedora",
    imageSrc: "https://example.com/images/SKU41.jpg",
    category: EProductCategory.HAT,
    price: 41.5,
    sizes: [EProductSize.M],
    tones: [EProductTone.WHITE, EProductTone.COOL],
  },
  {
    sku: "SKU42",
    name: "Basic T-Shirt",
    imageSrc: "https://example.com/images/SKU42.jpg",
    category: EProductCategory["T-SHIRT"],
    price: 20.99,
    sizes: [EProductSize.S, EProductSize.M],
    tones: [EProductTone.WHITE, EProductTone.BLACK],
  },
  {
    sku: "SKU43",
    name: "Hiking Jeans",
    imageSrc: "https://example.com/images/SKU43.jpg",
    category: EProductCategory.JEANS,
    price: 55.25,
    sizes: [EProductSize.M, EProductSize.L],
    tones: [EProductTone.GRAY, EProductTone.WARM],
  },
  {
    sku: "SKU44",
    name: "Retro Glasses",
    imageSrc: "https://example.com/images/SKU44.jpg",
    category: EProductCategory.GLASSES,
    price: 48.0,
    sizes: [EProductSize.M],
    tones: [EProductTone.BLACK, EProductTone.COOL],
  },
  {
    sku: "SKU45",
    name: "Slip-On Sneakers",
    imageSrc: "https://example.com/images/SKU45.jpg",
    category: EProductCategory.SHOES,
    price: 80.8,
    sizes: [EProductSize.M, EProductSize.L],
    tones: [EProductTone.BLACK, EProductTone.GRAY],
  },
  {
    sku: "SKU46",
    name: "Summer Hat",
    imageSrc: "https://example.com/images/SKU46.jpg",
    category: EProductCategory.HAT,
    price: 25.95,
    sizes: [EProductSize.M, EProductSize.L],
    tones: [EProductTone.WHITE, EProductTone.COOL],
  },
  {
    sku: "SKU47",
    name: "T-Shirt with Pocket",
    imageSrc: "https://example.com/images/SKU47.jpg",
    category: EProductCategory["T-SHIRT"],
    price: 27.25,
    sizes: [EProductSize.M, EProductSize.L],
    tones: [EProductTone.BLACK, EProductTone.WHITE],
  },
  {
    sku: "SKU48",
    name: "Bootcut Denim",
    imageSrc: "https://example.com/images/SKU48.jpg",
    category: EProductCategory.JEANS,
    price: 65.55,
    sizes: [EProductSize.M, EProductSize.L],
    tones: [EProductTone.COOL, EProductTone.BLACK],
  },
  {
    sku: "SKU49",
    name: "Sport Sunglasses",
    imageSrc: "https://example.com/images/SKU49.jpg",
    category: EProductCategory.GLASSES,
    price: 85.0,
    sizes: [EProductSize.M],
    tones: [EProductTone.COOL, EProductTone.BLACK],
  },
  {
    sku: "SKU50",
    name: "Canvas Shoes",
    imageSrc: "https://example.com/images/SKU50.jpg",
    category: EProductCategory.SHOES,
    price: 60.5,
    sizes: [EProductSize.M, EProductSize.L],
    tones: [EProductTone.BLACK, EProductTone.GRAY],
  },
];
